### PR TITLE
fix app path

### PR DESCRIPTION
**Pull request by javascriptboss99**

### CODE REVIEW

**Comment by todda48** [comment]
I don't think this will work. For example if it's an S3 service you don't want 'files' in the path. 'files' is the service name for the storage service for the app.

**Comment by javascriptboss99** [comment]
the attribute name is "api_name" which I assume is the correct attribute to be used instead of value "files" everywhere ?

**Comment by leehicks** [comment]
1.x "api_name" is now just "name" in 2.0 (in some places the old "name" was
actually used as a label).

On Mon, Aug 3, 2015 at 5:01 PM, Andy Rai <notifications@github.com> wrote:

> the attribute name is "api_name" which I assume is the correct attribute
> to be used instead of value "files" everywhere ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreamfactorysoftware/df-admin-app/pull/16#issuecomment-127405475>
> .
>



-- 

*Lee Hicks *| Senior Software Engineer | DreamFactory Software, Inc.



http://www.dreamfactory.com
Follow us on  <http://www.facebook.com/dfsoftwareinc> Facebook
<http://www.facebook.com/dfsoftwareinc>
<http://www.linkedin.com/company/286888?trk=null> LinkedIn
<http://www.linkedin.com/company/286888?trk=null>
<http://twitter.com/#%21/dfsoftwareinc> Twitter
<http://twitter.com/#%21/dfsoftwareinc>

**Comment by javascriptboss99** [comment]
PR Updated.

**Pull request merged**
